inherit_gem:
  syntax_tree: config/rubocop.yml

require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Lint/DuplicateBranch:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Lint/UnreachableLoop:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/Documentation:
  Exclude:
    - lib/rexml/css_selector/queries/*.rb
    - test/**/*.rb
