inherit_gem:
  syntax_tree: config/rubocop.yml

require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
